### PR TITLE
v3.1.2

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thewchan** [comment]
@conda-forge-admin please rerender

**Comment by synapticarbors** [comment]
I wonder my the regro bot didn't pick up the last few versions that are up on pypi. @thewchan -- Thanks for catching that.

**Comment by thewchan** [comment]
@synapticarbors I updated the recipe to more recent grayskull output hope that's okay (assuming I didn't make any mistake)

**Comment by thewchan** [comment]
@synapticarbors ready for review and merge!

**Pull request merged**
